Updated workflows

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -53,6 +53,15 @@ jobs:
     timeout-minutes: 15 
     runs-on: ubuntu-latest
     steps:
+
+      - name: Dump env 💩
+        run: env | sort
+
+      - name: Dump GitHub context 💩
+        env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
+        run: echo "$GITHUB_CONTEXT"
+        
       - name: Checkout 🛎️
         uses: actions/checkout@v3
         with:
@@ -101,8 +110,8 @@ jobs:
 
       - name: Auto Commit Changes 👩‍💻
         uses: stefanzweifel/git-auto-commit-action@v4
-        # Only on branches
-        if: always() && ${{ startsWith(github.ref, 'refs/heads/') }} && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/alpha'
+        # Only on branches even on failures
+        if: ${{ (success() || failure()) && startsWith(github.ref, 'refs/heads/') }}
         with:
           commit_message: Added Missing Screenshots
           branch: ${{ env.GITHUB_REF_NAME }}
